version: '3'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./funkos-db:/var/lib/postgresql/data