version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funkos-nest
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./cert:/app/cert
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./funkos-db:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./funkos-mongo/data:/data/db
      - ./funkos-mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro